### ISSUE TITLE
I use this code in STM32

### ISSUE THREAD

**Issue by cyang812** [toots/shine#29]
I use libshine to compress wav file to mp3 file in STM32. STM32 is a ARM CM4 mcu with fpu. 

I use your code and I find is not so fast to compress realtime. 

Actually,I just test a short file with 64 frame, so I calculate the code has 0.75x realtime.

It's reasonable in stm32 casue this chip's frequence just 180Mhz. Have you ever run it in a similar chip?

I find your code has lots of change compare to the original libshine. I guess you want the code faster so you modify it, am I right?

I want to know the ram consumption, have you ever notice it? In my test is almost 100kB, I mean is very wonderful if the ram consumption less.

My English is real poor, I hope you can understand it.
Thank you very much.

**Comment by toots** [comment]
Hi!

Yes, the speed up may contingent to the speed of the CPU/board. What really matters is to compare with a reference implementation such as `lame`.

The code has been extensively changed since the original version, indeed, to make it a proper shared library (no global variables) and to support `MPEG 2.5`. Also we had a contributor making really awesome simplifications.

I have not really done a lot of investigation on memory usage. Let me know if you have something to report on that front.

I'm closing this since I don't think that this is a bug report. Thanks for sharing the feedback, though!
